# Generated by Django 5.0.1 on 2024-01-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
    ]
