# Generated by Django 5.0.1 on 2024-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
